apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garageservice
  template:
    metadata:
      labels:
        app: garageservice
    spec:
      containers:
        - name: garageservice
          image: xoddec/garageservice:latest