apiVersion: v1
kind: Service
metadata:
  name: garagenpservice-srv
spec:
  type: NodePort
  selector:
    app: garageservice
  ports:
    - name: garageservice
      protocol: TCP
      port: 8080
      targetPort: 8080